services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/certs:/etc/nginx/certs
      - ./.docker/nginx/vhost.d:/etc/nginx/vhost.d
      - ./.docker/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - evolution-net
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./.docker/certs:/etc/nginx/certs
      - ./.docker/nginx/vhost.d:/etc/nginx/vhost.d
      - ./.docker/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - evolution-net
    restart: always

  api:
    container_name: evolution_api
    image: atendai/evolution-api
    restart: always
    depends_on:
      - redis
      - postgres
    volumes:
      - evolution_instances:/evolution/instances
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - evolution-net

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    expose:
      - "6379"
    networks:
      - evolution-net

  postgres:
    container_name: postgres
    image: postgres:15
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - evolution-net

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  evolution-net:
    driver: bridge
